sonar.projectKey=ifs24038-pabwe2026-reactjs
sonar.projectName=ifs24038-pabwe2026-reactjs
sonar.projectVersion=1.0.0
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.test.js,src/**/*.test.jsx
sonar.exclusions=src/main.jsx,src/setupTests.js,src/test-utils.jsx,node_modules/**,coverage/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8

